# Generated by Django 2.0.2 on 2018-04-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('cipher', models.CharField(max_length=50)),
                ('volume', models.PositiveSmallIntegerField()),
                ('publishing_info', models.TextField()),
                ('on_loan', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='Suscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_card', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
    ]
