# Generated by Django 2.0.2 on 2018-04-03 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suscriber',
            new_name='Subscriber',
        ),
        migrations.AddField(
            model_name='book',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib.Subscriber'),
        ),
        migrations.AlterField(
            model_name='book',
            name='on_loan',
            field=models.BooleanField(verbose_name='On loan'),
        ),
    ]
